"""Constants for SAJ R5 Inverter Modbus."""

from dataclasses import dataclass

from homeassistant.components.number import NumberEntityDescription
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
    SensorEntityDescription,
)
from homeassistant.const import (
    UnitOfReactivePower,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
)


DOMAIN = "saj_modbus"
DEFAULT_NAME = "SAJ"
DEFAULT_SCAN_INTERVAL = 60
DEFAULT_PORT = 502
CONF_SAJ_HUB = "saj_hub"
ATTR_MANUFACTURER = "SAJ Electric"


@dataclass
class SajModbusNumberEntityDescription(NumberEntityDescription):
    """A class that describes SAJ number entities."""


NUMBER_TYPES: dict[str, list[SajModbusNumberEntityDescription]] = {
    "LimitPower": SajModbusNumberEntityDescription(
        key="limitpower",
        translation_key="limit_power",
        native_max_value=110,
        native_min_value=0,
        icon="mdi:solar-power",
        native_unit_of_measurement="%",
    )
}


@dataclass
class SajModbusSensorEntityDescription(SensorEntityDescription):
    """A class that describes SAJ sensor entities."""


COUNTER_SENSOR_TYPES: dict[str, list[SajModbusSensorEntityDescription]] = {
    "TodayEnergy": SajModbusSensorEntityDescription(
        key="todayenergy",
        translation_key="today_energy",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    "MonthEnergy": SajModbusSensorEntityDescription(
        key="monthenergy",
        translation_key="month_energy",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
    ),
    "YearEnergy": SajModbusSensorEntityDescription(
        key="yearenergy",
        translation_key="year_energy",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
    ),
    "TotalEnergy": SajModbusSensorEntityDescription(
        key="totalenergy",
        translation_key="total_energy",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    "TodayHour": SajModbusSensorEntityDescription(
        key="todayhour",
        translation_key="today_hour",
        native_unit_of_measurement=UnitOfTime.HOURS,
        icon="mdi:progress-clock",
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    "TotalHour": SajModbusSensorEntityDescription(
        key="totalhour",
        translation_key="total_hour",
        native_unit_of_measurement=UnitOfTime.HOURS,
        icon="mdi:progress-clock",
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
}

SENSOR_TYPES: dict[str, list[SajModbusSensorEntityDescription]] = {
    "DevType": SajModbusSensorEntityDescription(
        key="devtype",
        translation_key="device_type",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "SubType": SajModbusSensorEntityDescription(
        key="subtype",
        translation_key="sub_type",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "CommVer": SajModbusSensorEntityDescription(
        key="commver",
        translation_key="comms_protocol_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "SN": SajModbusSensorEntityDescription(
        key="sn",
        translation_key="serial_number",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "PC": SajModbusSensorEntityDescription(
        key="pc",
        translation_key="product_code",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "DV": SajModbusSensorEntityDescription(
        key="dv",
        translation_key="display_software_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "MCV": SajModbusSensorEntityDescription(
        key="mcv",
        translation_key="master_ctrl_software_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "SCV": SajModbusSensorEntityDescription(
        key="scv",
        translation_key="slave_ctrl_software_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "DispHWVersion": SajModbusSensorEntityDescription(
        key="disphwversion",
        translation_key="display_board_hardware_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "CtrlHWVersion": SajModbusSensorEntityDescription(
        key="ctrlhwversion",
        translation_key="control_board_hardware_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "PowerHWVersion": SajModbusSensorEntityDescription(
        key="powerhwversion",
        translation_key="power_board_hardware_version",
        icon="mdi:information-outline",
        entity_registry_enabled_default=False,
    ),
    "MPVStatus": SajModbusSensorEntityDescription(
        key="mpvstatus",
        translation_key="inverter_status",
        icon="mdi:information-outline",
    ),
    "MPVMode": SajModbusSensorEntityDescription(
        key="mpvmode",
        translation_key="inverter_working_mode",
        icon="mdi:information-outline",
    ),
    "FaultMSG": SajModbusSensorEntityDescription(
        key="faultmsg",
        translation_key="inverter_error_message",
        icon="mdi:message-alert-outline",
    ),
    "DateTime": SajModbusSensorEntityDescription(
        key="datetime",
        translation_key="inverter_date_and_time",
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock-outline",
        entity_registry_enabled_default=False,
    ),
    "PV1Volt": SajModbusSensorEntityDescription(
        key="pv1volt",
        translation_key="pv1_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV1Curr": SajModbusSensorEntityDescription(
        key="pv1curr",
        translation_key="pv1_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV1Power": SajModbusSensorEntityDescription(
        key="pv1power",
        translation_key="pv1_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "PV2Volt": SajModbusSensorEntityDescription(
        key="pv2volt",
        translation_key="pv2_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV2Curr": SajModbusSensorEntityDescription(
        key="pv2curr",
        translation_key="pv2_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV2Power": SajModbusSensorEntityDescription(
        key="pv2power",
        translation_key="pv2_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "PV3Volt": SajModbusSensorEntityDescription(
        key="pv3volt",
        translation_key="pv3_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV3Curr": SajModbusSensorEntityDescription(
        key="pv3curr",
        translation_key="pv3_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "PV3Power": SajModbusSensorEntityDescription(
        key="pv3power",
        translation_key="pv3_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "BusVolt": SajModbusSensorEntityDescription(
        key="busvolt",
        translation_key="bus_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "InvTempC": SajModbusSensorEntityDescription(
        key="invtempc",
        translation_key="inverter_temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "GFCI": SajModbusSensorEntityDescription(
        key="gfci",
        translation_key="gfci",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "Power": SajModbusSensorEntityDescription(
        key="power",
        translation_key="active_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "QPower": SajModbusSensorEntityDescription(
        key="qpower",
        translation_key="reactive_power",
        native_unit_of_measurement=UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
        icon="mdi:flash",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "PF": SajModbusSensorEntityDescription(
        key="pf",
        translation_key="power_factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L1Volt": SajModbusSensorEntityDescription(
        key="l1volt",
        translation_key="l1_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L1Curr": SajModbusSensorEntityDescription(
        key="l1curr",
        translation_key="l1_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L1Freq": SajModbusSensorEntityDescription(
        key="l1freq",
        translation_key="l1_frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:sine-wave",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L1DCI": SajModbusSensorEntityDescription(
        key="l1dci",
        translation_key="l1_dc_component",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L1Power": SajModbusSensorEntityDescription(
        key="l1power",
        translation_key="l1_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "L1PF": SajModbusSensorEntityDescription(
        key="l1pf",
        translation_key="l1_power_factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "L2Volt": SajModbusSensorEntityDescription(
        key="l2volt",
        translation_key="l2_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L2Curr": SajModbusSensorEntityDescription(
        key="l2curr",
        translation_key="l2_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L2Freq": SajModbusSensorEntityDescription(
        key="l2freq",
        translation_key="l2_frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:sine-wave",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L2DCI": SajModbusSensorEntityDescription(
        key="l2dci",
        translation_key="l2_dc_component",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L2Power": SajModbusSensorEntityDescription(
        key="l2power",
        translation_key="l2_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "L2PF": SajModbusSensorEntityDescription(
        key="l2pf",
        translation_key="l2_power_factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "L3Volt": SajModbusSensorEntityDescription(
        key="l3volt",
        translation_key="l3_voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L3Curr": SajModbusSensorEntityDescription(
        key="l3curr",
        translation_key="l3_current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L3Freq": SajModbusSensorEntityDescription(
        key="l3freq",
        translation_key="l3_frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:sine-wave",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L3DCI": SajModbusSensorEntityDescription(
        key="l3dci",
        translation_key="l3_dc_component",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    "L3Power": SajModbusSensorEntityDescription(
        key="l3power",
        translation_key="l3_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "L3PF": SajModbusSensorEntityDescription(
        key="l3pf",
        translation_key="l3_power_factor",
        device_class=SensorDeviceClass.POWER_FACTOR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    "ISO1": SajModbusSensorEntityDescription(
        key="iso1",
        translation_key="pv1_iso",
        native_unit_of_measurement="kΩ",
        icon="mdi:omega",
        entity_registry_enabled_default=False,
    ),
    "ISO2": SajModbusSensorEntityDescription(
        key="iso2",
        translation_key="pv2_iso",
        native_unit_of_measurement="kΩ",
        icon="mdi:omega",
        entity_registry_enabled_default=False,
    ),
    "ISO3": SajModbusSensorEntityDescription(
        key="iso3",
        translation_key="pv3_iso",
        native_unit_of_measurement="kΩ",
        icon="mdi:omega",
        entity_registry_enabled_default=False,
    ),
    "ISO4": SajModbusSensorEntityDescription(
        key="iso4",
        translation_key="pv_iso",
        native_unit_of_measurement="kΩ",
        icon="mdi:omega",
        entity_registry_enabled_default=False,
    ),
    "ErrorCount": SajModbusSensorEntityDescription(
        key="errorcount",
        translation_key="error_count",
        icon="mdi:counter",
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
}

DEVICE_STATUSSES = {
    0: "Not Connected",
    1: "Waiting",
    2: "Normal",
    3: "Error",
    4: "Upgrading",
}

FAULT_MESSAGES = {
    0: {
        0x80000000: "Code 81: Lost Communication D<->C",
        0x00080000: "Code 48: Master Fan4 Error",
        0x00040000: "Code 47: Master Fan3 Error",
        0x00020000: "Code 46: Master Fan2 Error",
        0x00010000: "Code 45: Master Fan1 Error",
        0x00002000: "Code 43: Master HW Phase3 Current High",
        0x00001000: "Code 42: Master HW Phase2 Current High",
        0x00000800: "Code 41: Master HW Phase1 Current High",
        0x00000400: "Code 40: Master HWPV2 Current High",
        0x00000200: "Code 39: Master HWPV1 Current High",
        0x00000100: "Code 38: Master HWBus Voltage High",
        0x00000010: "Code 37: Master Phase3 Current High",
        0x00000008: "Code 36: Master Phase2 Current High",
        0x00000004: "Code 35: Master Phase1 Current High",
        0x00000002: "Code 34: Master Bus Voltage Low",
        0x00000001: "Code 33: Master Bus Voltage High",
    },
    1: {
        0x80000000: "Code 32: Master Bus Voltage Balance Error",
        0x40000000: "Code 31: Master ISO Error",
        0x20000000: "Code 30: Master Phase3 DCI Error",
        0x10000000: "Code 29: Master Phase2 DCI Error",
        0x08000000: "Code 28: Master Phase1 DCI Error",
        0x04000000: "Code 27: Master GFCI Error",
        0x02000000: "Code 26: Master Phase3 No Grid Error",
        0x01000000: "Code 25: Master Phase2 No Grid Error",
        0x00800000: "Code 24: Master Phase1 No Grid Error",
        0x00400000: "Code 23: Master Phase3 Frequency Low",
        0x00200000: "Code 22: Master Phase3 Frequency High",
        0x00100000: "Code 21: Master Phase2 Frequency Low",
        0x00080000: "Code 20: Master Phase2 Frequency High",
        0x00040000: "Code 19: Master Phase1 Frequency Low",
        0x00020000: "Code 18: Master Phase1 Frequency High",
        0x00010000: "Code 17: Master Phase3 Voltage 10Min High",
        0x00008000: "Code 16: Master Phase2 Voltage 10Min High",
        0x00004000: "Code 15: Master Phase1 Voltage 10Min High",
        0x00002000: "Code 14: Master Phase3 Voltage Low",
        0x00001000: "Code 13: Master Phase3 Voltage High",
        0x00000800: "Code 12: Master Phase2 Voltage Low",
        0x00000400: "Code 11: Master Phase2 Voltage High",
        0x00000200: "Code 10: Master Phase1 Voltage Low",
        0x00000100: "Code 09: Master Phase1 Voltage High",
        0x00000080: "Code 08: Master Current Sensor Error",
        0x00000040: "Code 07: Master DCI Device Error",
        0x00000020: "Code 06: Master GFCI Device Error",
        0x00000010: "Code 05: Master Lost Communication M<->S",
        0x00000008: "Code 04: Master Temperature Low Error",
        0x00000004: "Code 03: Master Temperature High Error",
        0x00000002: "Code 02: Master EEPROM Error",
        0x00000001: "Code 01: Master Relay Error",
    },
    2: {
        0x40000000: "Code 80: Slave PV Voltage High Error",
        0x20000000: "Code 79: Slave PV2 Current High Error",
        0x10000000: "Code 78: Slave PV1 Current High Error",
        0x08000000: "Code 77: Slave PV2 Voltage High Error",
        0x04000000: "Code 76: Slave PV1 Voltage High Error",
        0x02000000: "Code 75: Slave Phase3 No Grid Error",
        0x01000000: "Code 74: Slave Phase2 No Grid Error",
        0x00800000: "Code 73: Slave Phase1 No Grid Error",
        0x00400000: "Code 72: Slave Phase3 Frequency Low",
        0x00200000: "Code 71: Slave Phase3 Frequency High",
        0x00100000: "Code 70: Slave Phase2 Frequency Low",
        0x00080000: "Code 69: Slave Phase2 Frequency High",
        0x00040000: "Code 68: Slave Phase1 Frequency Low",
        0x00020000: "Code 67: Slave Phase1 Frequency High",
        0x00010000: "Code 66: Slave Phase3 Voltage Low",
        0x00008000: "Code 65: Slave Phase3 Voltage High",
        0x00004000: "Code 64: Slave Phase2 Voltage Low",
        0x00002000: "Code 63: Slave Phase2 Voltage High",
        0x00001000: "Code 62: Slave Phase1 Voltage Low",
        0x00000800: "Code 61: Slave Phase1 Voltage High",
        0x00000400: "Code 60: Slave Phase3 DCI Consis Error",
        0x00000200: "Code 59: Slave Phase2 DCI Consis Error",
        0x00000100: "Code 58: Slave Phase1 DCI Consis Error",
        0x00000080: "Code 57: Slave GFCI Consis Error",
        0x00000040: "Code 56: Slave Phase3 Frequency Consis Error",
        0x00000020: "Code 55: Slave Phase2 Frequency Consis Error",
        0x00000010: "Code 54: Slave Phase1 Frequency Consis Error",
        0x00000008: "Code 53: Slave Phase3 Voltage Consis Error",
        0x00000004: "Code 52: Slave Phase2 Voltage Consis Error",
        0x00000002: "Code 51: Slave Phase1 Voltage Consis Error",
        0x00000001: "Code 50: Slave Lost Communication between M<->S",
    },
}
